title: "Arjun Ganesan"
description: "Personal Website"
baseurl: ""  # leave empty for user.github.io
url: "https://arjun-ganesan.github.io"

# Build settings
theme: minima
markdown: kramdown
permalink: /:title/

# Navigation menu
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "Projects"
    link: /projects
